name: Deploy SSIS Packages to SQL Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-ssis:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify SSIS project exists
      run: |
        $projectPath = "${{ github.workspace }}\MigratingTimesheet"
        if (-not (Test-Path "$projectPath\MigratingTimesheet.dtproj")) {
            Write-Error "SSIS project file not found at expected location: $projectPath"
            exit 1
        }
        Write-Output "✅ SSIS project file found at: $projectPath"
        Get-ChildItem -Path $projectPath -Recurse
      shell: pwsh

    - name: Setup SSIS DevOps Tools
      uses: jonlabelle/setup-ssis-devops-tools@v1

    - name: Build SSIS Project
      run: |
        $projectPath = "${{ github.workspace }}\MigratingTimesheet\MigratingTimesheet.dtproj"
        $outputPath = "${{ runner.temp }}\SSISOutput"

        if (-not (Test-Path $outputPath)) {
            New-Item -ItemType Directory -Path $outputPath -Force
        }

        SSISBuild.exe -p:"$projectPath" -o:"$outputPath" -v:Diagnostic

        if (-not (Test-Path "$outputPath\MigratingTimesheet.ispac")) {
            Write-Error "❌ Build failed — .ispac file not found"
            exit 1
        }
        Write-Output "✅ Build completed successfully: $outputPath\MigratingTimesheet.ispac"
      shell: pwsh

    - name: Deploy SSIS Package
      env:
        SQL_SERVER: "LAPTOP-62JJ49T4"
        SSIS_CATALOG: "SSISDB"
        SSIS_FOLDER: "TimesheetDeploy"
        SSIS_PROJECT: "MigratingTimesheet"
      run: |
        $ispacPath = "${{ runner.temp }}\SSISOutput\MigratingTimesheet.ispac"
        $folderPath = "/SSISDB/$($env:SSIS_FOLDER)/$($env:SSIS_PROJECT)"

        SSISDeploy.exe -s:"$ispacPath" -d:"catalog;$folderPath;$($env:SQL_SERVER)" -at:Windows -v:Diagnostic

        if ($LASTEXITCODE -eq 0) {
          Write-Output "✅ SSIS Project deployed successfully to $($env:SSIS_CATALOG)/$($env:SSIS_FOLDER)"
        } else {
          Write-Error "❌ Deployment failed for $($env:SSIS_PROJECT)"
          exit 1
        }
      shell: pwsh
