# .github/workflows/test-runner.yml
name: Self-Hosted Runner Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, windows]

    steps:
      - name: Show user info
        run: whoami
