name: Deploy SSIS Packages to SQL Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-ssis:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug workspace
      run: |
        Write-Output "Workspace path: ${{ github.workspace }}"
        Get-ChildItem -Path "${{ github.workspace }}" -Recurse
      shell: powershell

    - name: Verify SSIS Project
      run: |
        $projectPath = "${{ github.workspace }}\MigratingTimesheet"
        if (-not (Test-Path "$projectPath\MigratingTimesheet.dtproj")) {
            Write-Error "SSIS project file not found at: $projectPath"
            exit 1
        }
        Write-Output "SSIS project found at: $projectPath"
      shell: powershell

    - name: Verify Build Tool
      run: |
        $buildToolsPath = "C:\ssis-tools\SSISBuild.exe"
        if (-not (Test-Path $buildToolsPath)) {
            Write-Error "SSISBuild.exe not found at $buildToolsPath"
            exit 1
        }
        Write-Output "SSISBuild.exe found at: $buildToolsPath"
      shell: powershell

    - name: Build SSIS Project
      run: |
        $projectPath = "${{ github.workspace }}\MigratingTimesheet\MigratingTimesheet.dtproj"
        $outputPath = "${{ runner.temp }}\SSISOutput"
        $config = "Development"

        if (-not (Test-Path $outputPath)) {
            New-Item -ItemType Directory -Path $outputPath -Force
        }

        & "C:\ssis-tools\SSISBuild.exe" -p:"$projectPath" -o:"$outputPath" -c:"$config" -l:DIAG

        $ispacPath = Join-Path $outputPath "$config\MigratingTimesheet.ispac"
        if (-not (Test-Path $ispacPath)) {
            Write-Error "Build failed - .ispac not created at: $ispacPath"
            exit 1
        }

        Write-Output "Build completed successfully. ISPAC path: $ispacPath"
      shell: powershell

    - name: Deploy ISPAC using ISDeploymentWizard
      env:
        SQL_SERVER: "LAPTOP-62JJ49T4"
        SSIS_FOLDER: "TimesheetDeploy"
        SSIS_PROJECT: "MigratingTimesheet"
      run: |
        $ispacPath = "${{ runner.temp }}\SSISOutput\Development\MigratingTimesheet.ispac"

        # Find ISDeploymentWizard.exe
        $possiblePaths = @(
            "C:\Program Files\Microsoft SQL Server\160\DTS\Binn\ISDeploymentWizard.exe",
            "C:\Program Files (x86)\Microsoft SQL Server\160\DTS\Binn\ISDeploymentWizard.exe",
            "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\SSIS\160\Binn\ISDeploymentWizard.exe",
            "C:\Program Files (x86)\Microsoft SQL Server Management Studio 20\Common7\IDE\CommonExtensions\Microsoft\SSIS\160\Binn\ISDeploymentWizard.exe"
        )

        $wizardPath = $possiblePaths | Where-Object { Test-Path $_ } | Select-Object -First 1

        if (-not $wizardPath) {
            Write-Error "ISDeploymentWizard.exe not found in known locations"
            exit 1
        }

        Write-Output "Using ISDeploymentWizard at: $wizardPath"

        & $wizardPath /Silent /Model:Project /SourceFile:"$ispacPath" /DestinationServer:$env:SQL_SERVER /DestinationPath:"/SSISDB/$($env:SSIS_FOLDER)"
        
        if ($LASTEXITCODE -eq 0) {
            Write-Output "SSIS Project deployed successfully to SSISDB\$($env:SSIS_FOLDER)"
        } else {
            Write-Error "Deployment failed with exit code $LASTEXITCODE"
            exit 1
        }
      shell: powershell
