name: SSIS Build and Deploy

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: self-hosted  # Use self-hosted runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup SSIS tools
      - name: Setup SQL Server SSIS DevOps Tools
        uses: jonlabelle/setup-ssis-devops-tools@v1

      # Step 3: Build SSIS project
      - name: Build SSIS Package
        run: |
          mkdir "SSISOutput" -Force
          SSISBuild.exe -p:"MigratingTimesheet\MigratingTimesheet.dtproj" -o:"SSISOutput" -c:Development

      # Step 4: Verify build output
      - name: Verify .ispac file
        run: |
          dir "SSISOutput\Development"

      # Step 5: Test SQL Server Connectivity
      - name: Test SQL Server Connectivity
        run: |
          Test-NetConnection -ComputerName LAPTOP-62JJ49T4 -Port 1433

      # Step 6: Deploy SSIS Package
      - name: Deploy SSIS Package
        run: |
          $ispacPath = "SSISOutput\Development\MigratingTimesheet.ispac"
          SSISDeploy.exe `
            -s:"$ispacPath" `
            -d:"catalog;/SSISDB/TimesheetDeploy/MigratingTimesheet;LAPTOP-62JJ49T4" `
            -at:SQL `
            -u:"Auto_user" `
            -p:"SecurePass2025" `
            -v:Verbose > deploy_output.txt 2>&1
          type deploy_output.txt

      # Step 7: Upload deploy output as artifact
      - name: Upload deploy output as artifact
        if: always()  # Run even if deployment fails
        uses: actions/upload-artifact@v4
        with:
          name: deploy-output
          path: deploy_output.txt
