name: SSIS Build and Deploy

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Setup SSIS tools
    - name: Setup SQL Server SSIS DevOps Tools
      uses: jonlabelle/setup-ssis-devops-tools@v1

    # Step 3: Build SSIS project
    - name: Build SSIS Package
      run: |
        mkdir "C:\a\testing-repo\testing-repo\SSISOutput" -Force
        SSISBuild.exe -p:"C:\a\testing-repo\testing-repo\MigratingTimesheet\MigratingTimesheet.dtproj" -o:"C:\a\testing-repo\testing-repo\SSISOutput" -c:Development

    # Step 4: Verify build output
    - name: Verify .ispac file
      run: |
        dir "C:\a\testing-repo\testing-repo\SSISOutput\Development"

    # Step 5: Deploy using Windows Auth
    - name: Deploy SSIS Package
      run: |
        SSISDeploy.exe -s:"C:\a\testing-repo\testing-repo\SSISOutput\Development\MigratingTimesheet.ispac" -d:"catalog;/SSISDB/TimesheetDeploy/MigratingTimesheet;rnjva-197-184-114-37.a.free.pinggy.link,45825" -at:Windows -conf:Development
