name: Deploy SSIS Packages to SQL Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-ssis:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify SSIS project exists
      run: |
        $projectPath = "${{ github.workspace }}\MigratingTimesheet"
        if (-not (Test-Path "$projectPath\MigratingTimesheet.dtproj")) {
            Write-Error "❌ SSIS project file not found at: $projectPath"
            exit 1
        }
        Write-Output "✅ SSIS project found at: $projectPath"
        Get-ChildItem -Path $projectPath -Recurse
      shell: powershell

    - name: Build SSIS Project using SSISBuild.exe
      run: |
        $projectPath = "${{ github.workspace }}\MigratingTimesheet\MigratingTimesheet.dtproj"
        $outputPath = "${{ runner.temp }}\SSISOutput"

        if (-not (Test-Path $outputPath)) {
            New-Item -ItemType Directory -Path $outputPath -Force
        }

        & "C:\ssis-tools\SSISBuild.exe" -p:"$projectPath" -o:"$outputPath" -l:DIAG

        if (-not (Test-Path "$outputPath\MigratingTimesheet.ispac")) {
            Write-Error "❌ Build failed — .ispac not created."
            exit 1
        }

        Write-Output "✅ Build completed successfully. ISPAC path: $outputPath\MigratingTimesheet.ispac"
      shell: powershell

    - name: Deploy SSIS Package using SSISDeploy.exe
      env:
        SQL_SERVER: "LAPTOP-62JJ49T4"
        SSIS_CATALOG: "SSISDB"
        SSIS_FOLDER: "TimesheetDeploy"
        SSIS_PROJECT: "MigratingTimesheet"
      run: |
        $ispacPath = "${{ runner.temp }}\SSISOutput\MigratingTimesheet.ispac"
        $folderPath = "/SSISDB/$($env:SSIS_FOLDER)/$($env:SSIS_PROJECT)"

        & "C:\ssis-tools\SSISDeploy.exe" -s:"$ispacPath" -d:"catalog;$folderPath;$($env:SQL_SERVER)" -at:Windows -l:DIAG

        if ($LASTEXITCODE -eq 0) {
            Write-Output "✅ SSIS Project deployed successfully to $($env:SSIS_CATALOG)/$($env:SSIS_FOLDER)"
        } else {
            Write-Error "❌ Deployment failed"
            exit 1
        }
      shell: powershell
