name: Deploy SSIS Packages to SQL Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-ssis:
    runs-on: self-hosted

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Debug workspace path
    - name: Debug workspace path
      run: |
        Write-Output "Workspace path: ${{ github.workspace }}"
        Get-ChildItem -Path "${{ github.workspace }}" -Recurse
      shell: powershell

    # Verify SSIS project exists
    - name: Verify SSIS project exists
      run: |
        $projectPath = "${{ github.workspace }}\MigratingTimesheet"
        if (-not (Test-Path "$projectPath\MigratingTimesheet.dtproj")) {
            Write-Error "SSIS project file not found at: $projectPath"
            exit 1
        }
        Write-Output "SSIS project found at: $projectPath"
        Get-ChildItem -Path $projectPath -Recurse
      shell: powershell

    # Verify SSIS Tools
    - name: Verify SSIS Tools
      run: |
        $buildToolsPath = "C:\ssis-tools"
        $dtutilPath = "C:\Program Files\Microsoft SQL Server\160\DTS\Binn\dtutil.exe"
        if (-not (Test-Path "$buildToolsPath\SSISBuild.exe")) {
            Write-Error "SSISBuild.exe not found at: $buildToolsPath"
            exit 1
        }
        if (-not (Test-Path $dtutilPath)) {
            Write-Error "dtutil.exe not found at: $dtutilPath"
            exit 1
        }
        Write-Output "SSIS tools found: SSISBuild.exe at $buildToolsPath, dtutil.exe at $dtutilPath"
      shell: powershell

    # Build SSIS Project using SSISBuild.exe
    - name: Build SSIS Project
      run: |
        $projectPath = "${{ github.workspace }}\MigratingTimesheet\MigratingTimesheet.dtproj"
        $outputPath = "${{ runner.temp }}\SSISOutput"
        $config = "Development"

        if (-not (Test-Path $outputPath)) {
            New-Item -ItemType Directory -Path $outputPath -Force
        }

        & "C:\ssis-tools\SSISBuild.exe" -p:"$projectPath" -o:"$outputPath" -c:"$config" -l:DIAG

        $ispacPath = Join-Path $outputPath "$config\MigratingTimesheet.ispac"
        if (-not (Test-Path $ispacPath)) {
            Write-Error "Build failed - .ispac not created at: $ispacPath"
            Get-ChildItem -Path $outputPath -Recurse
            exit 1
        }

        Write-Output "Build completed successfully. ISPAC path: $ispacPath"
      shell: powershell

    # Deploy SSIS Package using dtutil
    - name: Deploy SSIS Package
      env:
        SQL_SERVER: "LAPTOP-62JJ49T4"
        SSIS_CATALOG: "SSISDB"
        SSIS_FOLDER: "TimesheetDeploy"
        SSIS_PROJECT: "MigratingTimesheet"
      run: |
        $ispacPath = "${{ runner.temp }}\SSISOutput\Development\MigratingTimesheet.ispac"
        $folderPath = "/SSISDB/$($env:SSIS_FOLDER)/$($env:SSIS_PROJECT)"
        $dtutilPath = "C:\Program Files\Microsoft SQL Server\160\DTS\Binn\dtutil.exe"

        # Create folder in SSISDB if it doesn't exist
        & $dtutilPath /SQL "$($env:SSIS_FOLDER)" /EXISTS | Out-Null
        if ($LASTEXITCODE -ne 0) {
            & $dtutilPath /SQL "$($env:SSIS_FOLDER)" /CREATE
            if ($LASTEXITCODE -ne 0) {
                Write-Error "Failed to create SSISDB folder: $($env:SSIS_FOLDER)"
                exit 1
            }
        }

        # Deploy the .ispac file
        & $dtutilPath /FILE "$ispacPath" /DESTServer "$($env:SQL_SERVER)" /COPY SQL;"$folderPath" /QUIET
        if ($LASTEXITCODE -eq 0) {
            Write-Output "SSIS Project deployed successfully to $($env:SSIS_CATALOG)/$($env:SSIS_FOLDER)"
        } else {
            Write-Error "Deployment failed with exit code $LASTEXITCODE"
            exit 1
        }
      shell: powershell
